# Use root/example as user/password credentials
version: '3'
services:
  mysql_db:
    image: mysql
    container_name: placesmysqlcontainer
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretmysqlpassword
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: secret
    volumes:
      - $PWD/_mysql_databas/my/own/datadir:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 1020:1020
      # - 8080:8080

  redis:
    image: redis:7
    container_name: redisstorycontainer
    ports:
      - '6379:6379'
    volumes: 
      - redis_database:/data

  minio:
    image: minio/minio:latest
    container_name: miniostorycontainer
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - '$PWD/_minio_storage:/data'
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: StrongPassword#111
    command: server --console-address ":9001" /data

volumes:
  mysql_databas:
    driver: local
  minio_storage: {}
  redis_database:
    driver: local
