# Use root/example as user/password credentials
version: '3'
services:
  mariadb:
    # Resource: https://mariadb.com/kb/en/mariadb-basics/

    # Get into database
    # $ sudo mariadb -u root -p -h localhost
    # $ mysql -u [username] -p[password]
    # Resource: https://www.sqlshack.com/how-to-backup-and-restore-mysql-databases-using-the-mysqldump-command/
    # Resource: https://mariadb.com/kb/en/uuid/
    # Resource: https://mariadb.com/docs/skysql-dbaas/ref/cs10.5/cli/mariadb-dump/
    image: mariadb:11
    container_name: placesmariadbcontainer
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mariadatabase
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: secret
    # port:
    #   - 3306:3306
    volumes:
      - $PWD/_mariadb_database/:/var/lib/mysql
      # - ./dev/mariadb:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4
    container_name: placesadminercontainer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

  redis:
    image: redis:7
    container_name: placesrediscontainer
    ports:
      - '6379:6379'
    volumes: 
      - redis_database:/data

  minio:
    image: minio/minio:latest
    container_name: placesminiocontainer
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - '$PWD/_minio_storage:/data'
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: StrongPassword#111
    command: server --console-address ":9001" /data

volumes:
  _mariadb_databas:
    driver: local
  _minio_storage: {}
  redis_database:
    driver: local
