version: '3'
services:
  mariadb:
    image: mariadb:11
    container_name: placesmariadbcontainer
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856 # Set max_allowed_packet to 256M (or any other value)
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mariadatabase
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: secret
    ports:
      - 1022:3306
    volumes:
      - $PWD/_mariadb_database/:/var/lib/mysql

  adminer:
    image: adminer:4
    container_name: placesadminercontainer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

  redis:
    image: redis:7
    container_name: placesrediscontainer
    ports:
      - '6379:6379'
    volumes: 
      - redis_database:/data

  minio:
    image: minio/minio:latest
    container_name: placesminiocontainer
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - '$PWD/_minio_storage:/data'
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: StrongPassword#111
    command: server --console-address ":9001" /data

volumes:
  _mariadb_databas:
    driver: local
  _minio_storage: {}
  redis_database:
    driver: local
